// Web-ready images served from client/public/images (generated by
// `node script/optimize-images.mjs`). These are ILLUSTRATIVE stock-style
// visuals used as hero/section backdrops until the owner supplies real
// clinic photography. None of them depict patients' results or the team.
//
// To swap in a real photo: drop the original into attached_assets/, add it to
// HEROES in the script, run it, and point the entry below at the new name.

import type { CategorySlug } from "@/content/services/types";

export interface WebImage {
  /** Largest rendition, used as `src`. */
  src: string;
  /** `srcset` with width descriptors. */
  srcSet: string;
  alt: string;
}

function hero(name: string, alt: string): WebImage {
  return {
    src: `/images/hero/${name}-1920.webp`,
    srcSet: `/images/hero/${name}-1280.webp 1280w, /images/hero/${name}-1920.webp 1920w`,
    alt,
  };
}

export const IMG = {
  clinicSmile: hero("hero-clinic-smile", "Smiling patient during a dental check-up with the Dubai skyline behind"),
  implants: hero("hero-implants", "Illustration of a dental implant with a ceramic crown between natural teeth"),
  crowns: hero("hero-crowns", "Dental laboratory models with ceramic crowns and bridges"),
  treatmentPlan: hero("visual-treatment-plan", "Dentist explaining a digital treatment plan to a patient"),
  handshake: hero("visual-handshake", "Dentist welcoming a patient at the clinic reception"),
  team: hero("hero-team", "Dental team in a modern clinic"),
  reception: hero("visual-reception", "Modern dental clinic reception area"),
} as const;

/** Hero backdrop per treatment category (used by SubServicePage). */
export const CATEGORY_HERO: Record<CategorySlug, WebImage> = {
  "dental-surgery": IMG.treatmentPlan,
  "general-preventive": IMG.clinicSmile,
  "crowns-bridges": IMG.crowns,
  whitening: IMG.clinicSmile,
  orthodontics: IMG.treatmentPlan,
  restorative: IMG.crowns,
};

/** Intro-section visual per category. */
export const CATEGORY_VISUAL: Record<CategorySlug, WebImage> = {
  "dental-surgery": IMG.implants,
  "general-preventive": IMG.treatmentPlan,
  "crowns-bridges": IMG.crowns,
  whitening: IMG.clinicSmile,
  orthodontics: IMG.clinicSmile,
  restorative: IMG.crowns,
};
